[package]
name = "llkp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "llkp"
path = "main.rs"

[dependencies]
minreq = { version = "*", features = ["https"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
